create schema boodschappenlijstje;

create table boodschappenlijstje.productgroepen (
       id numeric,
       naam varchar(50),
       image_naam varchar(50),
       sort_order numeric
);

create table boodschappenlijstje.producten (
       id numeric,
       naam varchar(50),
       image_naam varchar(50),
       eenheid varchar(20),
       product_groep_id numeric
);

create table boodschappenlijstje.boodschappenlijst (
       id        numeric,
       productId numeric,
       aantal    numeric
);

insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (1, 'Groenten', 'groenten-fruit.jpg', 10);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (2, 'Fruit', 'fruit.jpg', 20);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (3, 'Potgroenten', 'potgroenten.jpg', 40);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (4, 'Zuivel/boter', 'zuivel.jpg', 79);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (5, 'Pastasauzen/pasta', 'pasta.jpg', 77);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (6, 'Vlees', 'vlees.png', 45);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (7, 'Vleeswaren', 'vleeswaren.jpg', 50);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (8, 'Zuren', 'zuren.jpg', 75);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (9, 'Kaas', 'kaas.jpg', 55);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (10, 'Frisdrank', 'frisdranken.jpg', 100);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (11, 'Sappen', 'sappen.jpg', 110);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (12, 'Chips', 'chips.jpg', 120);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (13, 'Was/schoonmaakmiddel', 'wasmiddel.png', 80);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (14, 'Koek en snoep', 'koek-snoep.jpg', 116);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (15, 'Verzorging', 'verzorging.jpg', 85);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (16, 'Koffie', 'koffie.jpg', 115);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (17, 'Bakprodukten', 'bakprodukten.jpg', 64);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (18, 'Broodbeleg', 'broodbeleg.jpg', 65);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (19, 'Ontbijt', 'ontbijt.jpg', 60);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (20, 'Diepvries', 'diepvries.png', 66);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (21, 'Soep', 'soepen.jpg', 71);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (22, 'Vleesconserven', 'vleesconserven.jpg', 72);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (23, 'Mixen/werelds', 'mixen.jpg', 73);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (24, 'Rijst/mie', 'rijst.jpg', 74);
insert into boodschappenlijstje.productgroepen(id, naam, image_naam, sort_order) values (25, 'Sauzen', 'sauzen.jpg', 76);

insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(1, 'Sla', 'sla.jpg', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(2, 'Bloemkool', 'bloemkool.png', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(3, 'Sperziebonen', 'sperziebonen.jpg', 'GRAM', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(4, 'Aardappelen', 'zak_aardappels.png', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(5, 'Uien (rode)', 'rode_uien.jpg', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(6, 'Zuurkool', 'zuurkool-naturel.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(7, 'Boerenkool', 'boerenkool.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(8, 'Hutspot', 'hutspot.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(9, 'Slamix', 'slamix.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(10, 'Andijvie', 'andijvie.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(11, 'Bananen', 'bananen.jpg', 'STUKS', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(12, 'Elstar appels', 'elstar.jpg', 'ZAK', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(13, 'Granny Smith', 'granny-smith.jpg', 'STUKS', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(14, 'Jonagold', 'jonagold.jpg', 'STUKS', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(15, 'Mandarijnen', 'mandarijnen.jpg', 'ZAK', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(16, 'Druiven pitloos wit', 'druiven-wit.png', 'STUKS', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(17, 'Meloen galia', 'galia-meloen.jpg', 'STUKS', 2);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(18, 'Spinazie groot', 'spinazie.png', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(19, 'Spinazie klein', 'spinazie.png', 'POT_KLEIN', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(20, 'Doperwten', 'doperwten.png', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(21, 'Wortelen', 'worteltjes.png', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(22, 'Rode kool m. appel', 'rode-kool-appel.png', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(23, 'Rode bieten', 'rode-bieten.png', 'POT_KLEIN', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(24, 'Ananasschijven', 'ananasschijven.png', 'BLIK_KLEIN', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(25, 'Fruitcocktail', 'fruitcocktail.jpg', 'BLIK_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(26, 'Blue Band light', 'blue-band-light.png', 'FLES', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(27, 'Blue Band pakje', 'blue-band-pakje.jpg', 'STUKS', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(28, 'Vanillevla', 'vanillevla.png', 'PAK', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(29, 'Optimel Framboos', 'optimel-framboos.jpg', 'PAK', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(30, 'Optimel Mango-Passievrucht', 'optimel-mango-passievrucht.jpg', 'PAK', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(31, 'Slagroom', 'slagroom.jpg', 'FLES', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(32, 'Yoghurt', 'yoghurt.jpg', 'PAK', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(33, 'Macaroni', 'macaroni.jpg', 'ZAK', 24);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(34, 'Spaghetti', 'spaghetti.jpg', 'ZAK', 24);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(35, 'Mix voor macaroni/spaghetti', 'mix-voor-macaroni-spaghetti.jpeg', 'DOOS', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(37, 'Spaghettisaus Bolognese', 'spaghettisaus-bolognese.png', 'POT_GROOT', 5);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(38, 'Chicken Tonight Hawaii', 'chicken-tonight.jpg', 'POT_GROOT', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(39, 'Rijst', 'lassie-rijst.png', 'PAK', 24);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(40, 'Mie nestjes', 'mie-nestjes.png', 'DOOS', 24);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(41, 'Gehakt runder', 'rundergehakt.jpg', 'GRAM', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(42, 'Slavinken', 'slavinken.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(43, 'Zigeunerschnitzel', 'zigeunerschnitzel.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(44, 'Kipfilet 2st.', 'kipfilet-2stuks.jpg', 'PAK', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(45, 'Kipfilet 3st.', 'kipfilet-3stuks.jpg', 'PAK', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(46, 'Sausijsjes', 'sausijsjes.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(47, 'Kip vleugels', 'kipvleugels.jpg', 'PAK', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(48, 'Varkens/runder carre', 'varkenscarre.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(49, 'Schnitzel naturel', 'schnitzel-naturel.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(50, 'Kipschnitzel', 'kipschnitzel.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(51, 'Rookworst fijn', 'rookworst.png', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(52, 'Shoarma', 'shoarma.jpg', 'GRAM', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(53, 'Hamlappen', 'hamlappen.jpg', 'GRAM', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(54, 'Blikboterhamworst', 'boterhamworst.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(55, 'Sategehakt', 'sategehakt.png', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(56, 'Schouderham', 'schouderham.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(57, 'Schwarzwalder schinken', 'schwarzwalder-schinken.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(58, 'Zeeuws spek', 'zeeuws-spek.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(59, 'Katenspek', 'katenspek.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(60, 'Filet Americain', 'filet-americain.png', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(61, 'Leverworst', 'leverworst.png', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(62, 'Huzarensalade', 'huzarensalade.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(63, 'Augurken', 'augurken.jpg', 'POT_GROOT', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(64, 'Kroepoek normaal', 'kroepoek-normaal.jpg', 'ZAK', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(65, 'Kroepoek cassave', 'kroepoek-cassave.png', 'ZAK', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(66, 'Ketjap Manis', 'ketjap-manis.jpg', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(67, 'Mayonaise', 'mayonaise-calve.jpg', 'POT_GROOT', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(68, 'Remia fritessaus light', 'remia-fritessaus-light.jpg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(69, 'Curry Gewurz', 'curry.jpg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(70, 'Fritessaus Americain', 'fritessaus-americain.jpg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(71, 'Slasaus halfvol', 'calve-slasaus-halfvol.jpg', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(72, 'Diamantvet 2 ltr.', 'diamant-vet.jpg', 'FLES', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(73, 'Natuurazijn', 'natuurazijn.png', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(74, 'Whisky cocktail', 'calve-whiskey-cocktail.jpg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(76, 'Maggi soep', 'maggi-soep.jpg', 'FLES', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(77, 'Kerrie ananas', 'kerrie-ananas.jpg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(78, 'Tomaten-groentensoep', 'tomaten-groentesoep.jpg', 'PAK', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(79, 'Drinkbouillon tuinkruiden', 'maggi-drinkbouillon-tuinkruiden.png', 'POT_KLEIN', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(80, 'Bouillonblokjes', 'maggi-bouillonblokjes.jpg', 'DOOS', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(81, 'Vleesjus rundvlees', 'vleesjus-rundvlees.png', 'ZAK', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(82, 'Kaas stuk jong belegen', 'kaas-stuk.jpg', 'STUKS', 9);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(83, 'Geraspte kaas jong belegen', 'geraspte-kaas.png', 'ZAK', 9);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(84, 'Kaasblokjes jong belegen', 'kaasblokjes.png', 'ZAK', 9);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(85, 'Kruidenboter', 'kruidenboter.png', 'STUKS', 9);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(86, 'Cola light 4-pack 1,25 liter', 'cola-light-4pack.jpg', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(87, 'Cola 4-pack 1,25 liter', 'cola-4pack.png', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(88, 'Cola 1,5 liter', 'cola-1.5-liter.jpg', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(89, 'Cola light 1,5 liter', 'cola-light-1.5-liter.jpg', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(90, 'Sinas light', 'sinas-light.png', 'FLES', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(91, 'Spa orange', 'spa-orange.jpg', 'FLES', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(92, 'Hertog Jan bier krat', 'hertog-jan-krat.jpg', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(93, 'Port Tawny', 'port.png', 'FLES', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(94, 'Wicky oranje groot', 'wicky-groot-oranje.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(95, 'Wicky rose groot', 'wicky-groot-rose.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(96, 'Wicky oranje klein', 'wicky-klein-oranje.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(97, 'Wicky blauw klein', 'wicky-klein-blauw.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(98, 'Wicky rose klein', 'wicky-klein-rose.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(99, 'Wicky groen klein', 'wicky-klein-groen.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(100, 'Spa  bosvruchten', 'spa-bosvruchten.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(101, 'IJsthee citroen', 'ijsthee-citroen.png', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(102, 'IJsthee perzik', 'ijsthee-perzik.png', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(103, 'Harde worst', 'harde-worst.jpg', 'STUKS', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(104, 'Smac groot', 'smac.jpg', 'STUKS', 22);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(105, 'Sate balletjes', 'gehaktballetjes-in-sate.png', 'BLIK_KLEIN', 22);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(106, 'Cocktailworstjes', 'cocktailworstjes.jpg', 'BLIK_KLEIN', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(107, 'Toastjes (mini-crackers', 'lu-mini-crackers.jpg', 'DOOS', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(108, 'Pepsels stokjes', 'pepsels.png', 'ZAK', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(109, 'Chocomel halfvol', 'chocomelk-halfvol-liter.png', 'LITER', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(110, 'Andy lavendel', 'andy-lavendel.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(111, 'Dikbleek', 'dikbleek.png', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(112, 'Vaatwastabletten', 'vaatwastabletten.jpg', 'DOOS', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(113, 'Vaatwaszout', 'vaatwaszout.jpg', 'DOOS', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(114, 'Glansspoelmiddel', 'glansspoelmiddel.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(115, 'Omo vloeibaar blauwe dop', 'omo-vloeibaar-blauwe-dop.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(116, 'Omo vloeibaar paarse dop', 'omo-vloeibaar-paarse-dop.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(117, 'Schatkistjes', 'schatkistjes.jpg', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(118, 'Skittles uitdeelzakjes', 'skittles.png', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(119, 'Pepermunt', 'wilhelmina-pepermunt.jpg', 'PAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(120, 'Café noir', 'cafe-noir.png', 'PAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(121, 'Biskwie', 'biskwie.jpg', 'PAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(122, 'Brinkys', 'brinkys.jpg', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(123, 'Biskwie met kokos', 'kokos-biscuit.jpg', 'PAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(124, 'Shampoo iedere dag', 'shampoo-iedere-dag.jpg', 'FLES', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(125, 'Shampoo glans', 'shampoo-glans.png', 'FLES', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(126, 'Handzeep', 'palmolive-handzeep.png', 'PAK', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(127, 'Tandpasta', 'prodent-tandpasta-soft-mint.jpg', 'STUKS', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(128, 'Douchegel rose dop', 'derlon-douchegel.jpg', 'STUKS', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(129, 'Gel geel', 'gel.gif', 'POT_KLEIN', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(130, 'Billendoekjes Ikke doen', 'ikke-doen.jpg', 'ZAK', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(131, 'Wattenstaafjes', 'wattenstaafjes.jpg', 'PAK', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(132, 'Haarlak blauw', 'junior-haarlak.jpg', 'FLES', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(133, 'Fruitbiscuit Sultana-achtig', 'fruitbiscuit-appel.png', 'PAK', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(134, 'Italiaanse kruiden', 'italiaanse-kruiden-hartig.png', 'PAK', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(135, 'Oploskoffie', 'oploskoffie.jpg', 'POT_GROOT', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(136, 'Theezakjes 1 kop', 'theezakjes.png', 'DOOS', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(137, 'Koffie 250 gr Snelfiltermaling', 'de-koffie-snelfilter.jpg', 'PAK', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(138, 'Poedersuiker', 'poedersuiker.jpg', 'STUKS', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(139, 'Mix voor appeltaart', 'mix-voor-appeltaart.jpg', 'PAK', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(140, 'Mix voor eierpannekoeken', 'mix-voor-eierpannekoeken.jpg', 'PAK', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(141, 'Mix voor muffins naturel', 'mix-muffins.jpg', 'DOOS', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(142, 'Schenkstroop', 'schenkstroop.jpg', 'FLES', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(143, 'Pindakaas light', 'pindakaas-light.gif', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(144, 'Pita broodjes', 'pita-broodjes.jpg', 'ZAK', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(145, 'Kersenjam', 'kersenjam.jpg', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(146, 'Abrikozenjam', 'abrikozenjam.png', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(147, 'Aardbeienjam', 'aardbeienjam.png', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(148, 'Sandwichspread natural', 'sandwichspread.png', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(149, 'Appelstroop rinse', 'appelstroop.jpg', 'POT_KLEIN', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(150, 'Boterhamzakjes', 'boterhamzakjes.jpg', 'DOOS', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(151, 'Muesli met chocola', 'muesli-chocolade.png', 'DOOS', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(152, 'Rijstwafels', 'rijstwafels.png', 'PAK', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(153, 'Mini frites', 'mini-frites.png', 'ZAK', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(154, 'Frikandellen 20st.', 'frikandellen-20st.png', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(155, 'Kipfingers', 'kipfingers.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(156, 'Kroketten', 'kroketten.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(157, 'Gehaktballetjes in zout-zure saus', 'gehaktballetjes-zoet-zure-saus.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(158, 'Sate mild', 'sate-mild.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(159, 'Hamburgers', 'hamburgers.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(160, 'Bitterballen', 'bitterballen.jpg', 'ZAK', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(161, 'Cakemix', 'geen_afbeelding.jpg', 'PAK', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(164, 'Dubbelfris witte druif', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(165, 'Citroenthee 1 kops', 'geen_afbeelding.jpg', 'DOOS', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(166, 'Bosvruchtenthee 1 kops', 'geen_afbeelding.jpg', 'DOOS', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(167, 'Koffiemelkcups', 'geen_afbeelding.jpg', 'PAK', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(168, 'Mosterdrollade', 'mosterdrollade.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(169, 'Dubbelfris perzik +', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(170, 'Optimel Aardbei', 'optimel-aardbei.png', 'LITER', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(171, 'Dextro Energy Classic', 'geen_afbeelding.jpg', 'PAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(172, 'Sperziebonen', 'sperziebonen-pot.png', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(174, 'Kl pakjes chocomelk', 'geen_afbeelding.jpg', 'PAK', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(175, 'Vuilniszak blauw', 'geen_afbeelding.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(176, 'Snackerjacks bbq', 'geen_afbeelding.jpg', 'PAK', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(177, 'Snackerjacks cheese', 'geen_afbeelding.jpg', 'PAK', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(178, 'Gehaktschnitsels', 'gehaktschnitzels.png', 'PAK', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(179, 'Riblappen', 'riblappen.jpeg', 'GRAM', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(180, 'Soepgroenten', 'soepgroenten.jpeg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(181, 'Filterzakjes', 'geen_afbeelding.jpg', 'PAK', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(182, 'Sultana kaneel', 'geen_afbeelding.jpg', 'PAK', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(184, 'Dressing honing mosterd', 'geen_afbeelding.jpg', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(185, 'Boerenmetworst', 'boerenmetworst.jpeg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(186, 'Toiletblop eigenmerk', 'geen_afbeelding.jpg', 'STUKS', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(187, 'Kipfilet', 'kipfilet.jpeg', 'GRAM', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(188, 'Komkommer', 'komkommer.jpeg', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(189, 'Olijfolie', 'geen_afbeelding.jpg', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(190, 'Cristal clear citroen', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(191, 'Heksenkaas', 'geen_afbeelding.jpg', 'STUKS', 9);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(193, 'Tostibrood', 'geen_afbeelding.jpg', 'STUKS', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(194, 'Gourmetschotel', 'gourmetschotel.jpeg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(195, 'Scheermesjes blauw', 'geen_afbeelding.jpg', 'STUKS', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(196, 'Dubbelfris mandarijn', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(198, 'Zout', 'geen_afbeelding.jpg', 'POT_GROOT', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(199, 'Kerriepoeder', 'kerriepoeder.jpg', 'POT_KLEIN', 5);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(200, 'Plasticafval zk', 'geen_afbeelding.jpg', 'STUKS', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(201, 'Lekker toetje', 'lekker-toetje.jpeg', 'STUKS', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(202, 'Spekblokjes mager', 'spekblokjes.jpeg', 'PAK', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(204, 'Broccolli', 'broccoli.jpeg', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(205, 'Paprika rood', 'paprika-rood.jpeg', 'STUKS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(206, 'Biefstuk', 'biefstuk.png', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(207, 'Toilet blokje', 'geen_afbeelding.jpg', 'STUKS', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(208, 'Tomatensoep', 'tomatensoep.jpg', 'BLIK_GROOT', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(209, 'Tomatensoep klein', 'tomatensoep-klein.jpg', 'BLIK_GROOT', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(210, 'Badkamer reiniger 3g', 'geen_afbeelding.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(211, 'Crackers', 'geen_afbeelding.jpg', 'PAK', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(212, 'Sandwichspread tomaat', 'geen_afbeelding.jpg', 'POT_GROOT', 18);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(213, 'Matses', 'geen_afbeelding.jpg', 'DOOS', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(214, 'Crackers vezelrijk', 'geen_afbeelding.jpg', 'STUKS', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(215, 'Cocktailprikkers', 'geen_afbeelding.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(216, 'Sate prikkers', 'geen_afbeelding.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(217, 'Babi ketjap conimex', 'mix-voor-babi-ketjap.png', 'PAK', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(218, 'Maizena', 'maizena.jpeg', 'PAK', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(219, 'Zak zuurtjes', 'geen_afbeelding.jpg', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(220, 'Kipschnitsels ambachtelijk', 'kipschnitzel-ambachtelijk.jpeg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(221, 'Wicky rood klein', 'geen_afbeelding.jpg', 'STUKS', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(222, 'Mix voor kwarktaart naturel', 'geen_afbeelding.jpg', 'STUKS', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(223, 'Smokey BBQ Honey', 'remia-sweet-honey-bbq-saus.jpeg', 'FLES', 25);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(224, 'Voque deo rose', 'geen_afbeelding.jpg', 'FLES', 15);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(225, 'Schuursponsjes', 'geen_afbeelding.jpg', 'PAK', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(227, 'M&Ms', 'geen_afbeelding.jpg', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(228, 'Losse wraps', 'losse-wraps.jpg', 'ZAK', 23);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(229, 'Salami', 'geen_afbeelding.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(230, 'Verse hamburgers', 'verse-hamburger.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(231, 'Dubro badkamerreiniger', 'geen_afbeelding.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(232, 'Wicky groot rood', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(233, 'Wicky groot blauw', 'geen_afbeelding.jpg', 'PAK', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(234, 'Schuimpjes', 'geen_afbeelding.jpg', 'ZAK', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(235, 'Komo vuilniszak', 'geen_afbeelding.jpg', 'ZAK', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(236, 'Aanmaakblokjes', 'geen_afbeelding.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(237, 'Unox rookworst', 'geen_afbeelding.jpg', 'STUKS', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(238, 'Verse slagroom', 'verse-slagroom.jpg', 'PAK', 4);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(239, 'Hamblokjes', 'geen_afbeelding.jpg', 'PAK', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(240, 'Frikandel 5 st', 'geen_afbeelding.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(241, 'Sate saus', 'geen_afbeelding.jpg', 'ZAK', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(242, 'Suikervrije hagelslag', 'geen_afbeelding.jpg', 'DOOS', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(243, 'Saté schnitzel', 'sate-schnitzel.jpg', 'STUKS', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(244, 'Panneermeel', 'geen_afbeelding.jpg', 'DOOS', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(245, 'Slimpie aanmaak framb', 'geen_afbeelding.jpg', 'FLES', 11);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(246, 'Eiersalade', 'geen_afbeelding.jpg', 'STUKS', 7);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(247, 'Macaronigroenten', 'macaroni-groenten.jpg', 'DOOS', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(248, 'Gelatinebladen', 'geen_afbeelding.jpg', 'STUKS', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(249, 'Amandelmeel(koopmans', 'geen_afbeelding.jpg', 'DOOS', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(250, 'Bekertjes roomijs', 'geen_afbeelding.jpg', 'DOOS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(251, 'Omo vloeibaar rose dop', 'geen_afbeelding.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(252, 'Vanille ijs (oke)', 'geen_afbeelding.jpg', 'PAK', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(253, 'Rosekoek met smarties', 'geen_afbeelding.jpg', 'STUKS', 14);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(254, 'Radler 0.0', 'geen_afbeelding.jpg', 'STUKS', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(255, '7up', 'geen_afbeelding.jpg', 'FLES', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(256, 'Aardappelbolletjes', 'aardappelbolletjes.jpg', 'ZAK', 1);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(257, 'Wc eend', 'geen_afbeelding.jpg', 'FLES', 13);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(258, 'Pedaalemmerzakken', 'geen_afbeelding.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(259, 'Pedaalemmerzak 20 ltr', 'geen_afbeelding.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(260, 'Rosé bier', 'geen_afbeelding.jpg', 'FLES', 10);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(261, 'Muffin vormpjes', 'geen_afbeelding.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(262, 'Varkenshaas', 'varkenshaas.jpg', 'GRAM', 6);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(263, 'Mango', 'mango.jpg', 'POT_GROOT', 3);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(264, 'Erwtensoep klein', 'erwtensoep-klein.jpg', 'BLIK_KLEIN', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(265, 'Ijsblokzakjes', 'geen_afbeelding.jpg', 'DOOS', 19);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(266, 'Lijnzaad( zonnatura', 'geen_afbeelding.jpg', 'ZAK', 17);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(267, 'Agf afvalzk', 'geen_afbeelding.jpg', 'STUKS', 20);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(268, 'Thee winterglow', 'geen_afbeelding.jpg', 'DOOS', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(269, 'Ongezouten pindas', 'geen_afbeelding.jpg', 'ZAK', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(270, 'Ongezouten cashew', 'geen_afbeelding.jpg', 'ZAK', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(271, 'Pecannootjes', 'geen_afbeelding.jpg', 'ZAK', 12);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(272, 'Koffiepads dark', 'geen_afbeelding.jpg', 'ZAK', 16);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(273, 'Tomatencreme soep', 'geen_afbeelding.jpg', 'BLIK_KLEIN', 21);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(274, 'Teriakisaus', 'geen_afbeelding.jpg', 'FLES', 8);
insert into boodschappenlijstje.producten(id, naam, image_naam, eenheid, product_groep_id) values(275, 'Teriakiwoksaus', 'geen_afbeelding.jpg', 'FLES', 8);
